// Generated by CoffeeScript 1.3.3
(function() {
  var DedupFilter;

  DedupFilter = (function() {

    function DedupFilter(subFilter) {
      this.subFilter = subFilter;
    }

    DedupFilter.prototype.filter = function(allTerms) {
      var term, terms, _i, _len;
      if (this.subFilter != null) {
        allTerms = this.subFilter.filter(allTerms);
      }
      terms = [];
      for (_i = 0, _len = allTerms.length; _i < _len; _i++) {
        term = allTerms[_i];
        this.insertTermSync(terms, term);
      }
      return terms;
    };

    DedupFilter.prototype.insertTermSync = function(terms, term) {
      var i;
      i = 0;
      
      for (; i < terms.length && term > terms[i]; i++)
        ;
    ;

      if (i < terms.length && (term === terms[i])) {
        return;
      }
      terms.splice(i, 0, term);
    };

    return DedupFilter;

  })();

  module.exports = {
    DedupFilter: DedupFilter
  };

}).call(this);
