// Generated by CoffeeScript 1.3.3
(function() {
  var DocumentBuilder,
    __hasProp = {}.hasOwnProperty;

  DocumentBuilder = (function() {

    function DocumentBuilder(converter) {
      this.converter = converter;
      return;
    }

    DocumentBuilder.prototype.build = function(o) {
      var doc, field, fieldGetter, _ref;
      doc = {};
      _ref = this.converter;
      for (field in _ref) {
        if (!__hasProp.call(_ref, field)) continue;
        fieldGetter = _ref[field];
        doc[field] = fieldGetter(o);
      }
      return doc;
    };

    return DocumentBuilder;

  })();

  module.exports = {
    DocumentBuilder: DocumentBuilder
  };

}).call(this);
