// Generated by CoffeeScript 1.3.3
(function() {
  var DedupFilter, DocumentInverter, LowerCaseFilter, dedupFilter, lowerCaseFilter,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  dedupFilter = require('./DedupFilter.coffee');

  DedupFilter = dedupFilter.DedupFilter;

  lowerCaseFilter = require('./LowerCaseFilter.coffee');

  LowerCaseFilter = lowerCaseFilter.LowerCaseFilter;

  DocumentInverter = (function() {

    function DocumentInverter(filter) {
      this.tokenizeSync = __bind(this.tokenizeSync, this);

      this.insertTermSync = __bind(this.insertTermSync, this);

      this.invertSync = __bind(this.invertSync, this);
      this.filter = filter != null ? filter : new DedupFilter(new LowerCaseFilter());
    }

    DocumentInverter.prototype.invertSync = function(s) {
      var allTerms;
      allTerms = this.tokenizeSync(s);
      return this.filter.filter(allTerms);
    };

    DocumentInverter.prototype.insertTermSync = function(terms, term) {
      var i;
      i = 0;
      
      for (; i < terms.length && term > terms[i]; i++)
        ;
    ;

      if (i < terms.length && (term === terms[i])) {
        return;
      }
      terms.splice(i, 0, term);
    };

    DocumentInverter.prototype.tokenizeSync = function(s) {
      var match, pattern;
      pattern = /[a-z]+/ig;
      match = s.match(pattern);
      if (!(match === '' || match === null)) {
        return match;
      }
      return [];
    };

    return DocumentInverter;

  })();

  module.exports = {
    DocumentInverter: DocumentInverter
  };

}).call(this);
