// Generated by CoffeeScript 1.3.3
(function() {
  var BitArray, IndexSearcher;

  BitArray = require('bit-array');

  IndexSearcher = (function() {

    function IndexSearcher(index) {
      this.index = index;
    }

    IndexSearcher.prototype.searchAllIndexesSync = function(query) {
      var b, n, _i, _ref;
      b = new BitArray;
      if (this.index.count()) {
        for (n = _i = 0, _ref = this.index.count() - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; n = 0 <= _ref ? ++_i : --_i) {
          b.set(n, query.IsMatchAtIndex(n, this));
        }
      }
      return b;
    };

    IndexSearcher.prototype.searchAllIndexes = function(query, callback) {
      var _this = this;
      process.nextTick(function() {
        var x;
        x = _this.searchAllIndexesSync(query);
        callback(null, x);
      });
    };

    return IndexSearcher;

  })();

  module.exports = {
    IndexSearcher: IndexSearcher
  };

}).call(this);
