// Generated by CoffeeScript 1.3.3
(function() {
  var BitArray;

  BitArray = require('bit-array');

  module.exports.IndexSearcher = (function() {

    function IndexSearcher(index) {
      this.index = index;
    }

    IndexSearcher.prototype.searchAllIndexesSync = function(query) {
      return query.search(this.index);
    };

    IndexSearcher.prototype.searchAllIndexes = function(query, callback) {
      var _this = this;
      process.nextTick(function() {
        var x;
        x = _this.searchAllIndexesSync(query);
        callback(null, x);
      });
    };

    return IndexSearcher;

  })();

}).call(this);
