// Generated by CoffeeScript 1.3.3
(function() {

  module.exports.Query = (function() {

    function Query(matchProvider) {
      this.matchProvider = matchProvider;
      if (this.matchProvider == null) {
        throw new Error("Argument may not be null: " + matchProvider);
      }
    }

    Query.prototype.search = function(index) {
      return this.matchProvider(index);
    };

    return Query;

  })();

}).call(this);
